version : '3.3'

service:
  app:
    build: .
    container_name: node-app

    ports: 
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV
    networks:
      - node-net
    
networks:
  node=net:
    driver: bidge